// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjalcinvbuxuiozwxkwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYWxjaW52YnV4dWlvend4a3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzM4NTYsImV4cCI6MjA1NzcwOTg1Nn0.E4hMY-He7L5EUEgqXNgmagGAYd1CM1e8DcAK_fbOa6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);